FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY *.sln .
COPY **/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p $(dirname $file) && mv $file $(dirname $file); done
RUN dotnet restore

COPY . .
WORKDIR /app/Talabat.APIs
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/Talabat.APIs/out .

ENTRYPOINT ["dotnet", "Talabat.APIs.dll"]